# Generated by Django 2.0.4 on 2018-04-17 21:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Institutos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituto',
            old_name='votes',
            new_name='id_legado',
        ),
        migrations.RemoveField(
            model_name='instituto',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='instituto',
            name='celular',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instituto',
            name='ciudad',
            field=models.CharField(default='Montevideo', max_length=50),
        ),
        migrations.AddField(
            model_name='instituto',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='instituto',
            name='departamento',
            field=models.CharField(default='Montevideo', max_length=50),
        ),
        migrations.AddField(
            model_name='instituto',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='instituto',
            name='descripcion_corta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='instituto',
            name='direccion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='instituto',
            name='email_contacto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='instituto',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='instituto',
            name='logo',
            field=models.ImageField(default='images/profile_pics/blank-profile.jpg', upload_to='images/profile_pics/'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='longitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='instituto',
            name='modificado',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='instituto',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='instituto',
            name='pais',
            field=models.CharField(default='Uruguay', max_length=50),
        ),
        migrations.AddField(
            model_name='instituto',
            name='posicionamiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instituto',
            name='subtitulo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='instituto',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instituto',
            name='usuario',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='centro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comodidad',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facilidad',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='motivo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='redsocial',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
