# Generated by Django 2.0.3 on 2018-04-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0002_auto_20180417_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensajes',
            new_name='Mensaje',
        ),
    ]
