# Generated by Django 2.0.4 on 2018-05-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0003_auto_20180421_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituto',
            name='materias',
            field=models.ManyToManyField(to='Institutos.Materia'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Institutos.Centro'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='instituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Institutos.Instituto'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Institutos.Motivo'),
        ),
    ]
