# Generated by Django 2.0.5 on 2018-06-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0004_auto_20180517_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLegado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
