# Generated by Django 2.0.5 on 2018-06-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0006_auto_20180613_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituto',
            old_name='id_legado',
            new_name='referencia',
        ),
    ]
