# Generated by Django 2.0.5 on 2018-06-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0007_auto_20180613_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituto',
            name='email_contacto',
        ),
    ]
