# Generated by Django 2.0.5 on 2018-06-14 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0008_remove_instituto_email_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlace',
            name='instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Institutos.Instituto'),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='redSocial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Institutos.RedSocial'),
        ),
    ]
