# Generated by Django 2.0.5 on 2018-06-14 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0009_auto_20180614_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='modificado',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
