# Generated by Django 2.0.5 on 2018-06-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0010_auto_20180614_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariolegado',
            name='activo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
