# Generated by Django 2.0.5 on 2018-06-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0011_usuariolegado_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariolegado',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
