# Generated by Django 2.0.3 on 2018-08-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0012_auto_20180614_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='linkEnviado',
            field=models.BooleanField(default=False),
        ),
    ]
