# Generated by Django 2.0.5 on 2018-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0013_auto_20180817_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='hash_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
