# Generated by Django 2.0.5 on 2018-08-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0014_mensaje_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='emailVerificado',
            field=models.BooleanField(default=False),
        ),
    ]
