# Generated by Django 2.0.3 on 2018-11-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0015_mensaje_emailverificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituto',
            name='esDestacado',
            field=models.BooleanField(default=False),
        ),
    ]
