# Generated by Django 2.0.3 on 2018-11-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0016_instituto_esdestacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='referencia',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
