# Generated by Django 2.0.3 on 2018-11-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0017_auto_20181114_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='direccion',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
