# Generated by Django 2.0.3 on 2018-11-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0018_auto_20181114_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='esDestacado',
            field=models.NullBooleanField(default=False),
        ),
    ]
