# Generated by Django 2.0.3 on 2018-11-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0019_auto_20181114_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Omnibus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calle', to='Institutos.Calle')),
                ('esquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esquina', to='Institutos.Calle')),
                ('lineas', models.ManyToManyField(to='Institutos.Omnibus')),
            ],
        ),
    ]
