# Generated by Django 2.0.3 on 2018-11-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0021_instituto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='hash_id',
        ),
        migrations.AddField(
            model_name='instituto',
            name='hash_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
