# Generated by Django 2.0.3 on 2018-12-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0022_auto_20181126_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
