# Generated by Django 2.1.3 on 2018-12-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0023_mensaje_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
