# Generated by Django 2.1.3 on 2018-12-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0024_auto_20181211_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='descripcion_corta',
            field=models.CharField(default='', max_length=200),
        ),
    ]
