# Generated by Django 2.1.3 on 2018-12-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0025_auto_20181211_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='descripcion',
            field=models.CharField(default='', max_length=300),
        ),
    ]
