# Generated by Django 2.1.3 on 2018-12-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0028_auto_20181211_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='celular',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
