# Generated by Django 2.0.3 on 2018-12-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0029_auto_20181211_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='instituto',
        ),
        migrations.AddField(
            model_name='instituto',
            name='omnibuses',
            field=models.ManyToManyField(to='Institutos.Omnibus'),
        ),
        migrations.DeleteModel(
            name='Transporte',
        ),
    ]
