# Generated by Django 2.0.3 on 2018-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0030_auto_20181212_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariolegado',
            name='migrado',
            field=models.BooleanField(default=False),
        ),
    ]
