# Generated by Django 2.1.3 on 2018-12-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0031_usuariolegado_migrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='logo',
            field=models.ImageField(default='profile_pics/blank-profile.jpg', upload_to='profile_pics/'),
        ),
    ]
