# Generated by Django 2.1.3 on 2018-12-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0032_auto_20181226_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
        migrations.AlterField(
            model_name='instituto',
            name='barrios',
            field=models.ManyToManyField(blank=True, to='Institutos.Barrio'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='centros',
            field=models.ManyToManyField(blank=True, to='Institutos.Centro'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='comodidades',
            field=models.ManyToManyField(blank=True, to='Institutos.Comodidad'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='facilidades',
            field=models.ManyToManyField(blank=True, to='Institutos.Facilidad'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='formasPago',
            field=models.ManyToManyField(blank=True, to='Institutos.FormaPago'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='materias',
            field=models.ManyToManyField(blank=True, to='Institutos.Materia'),
        ),
    ]
