# Generated by Django 2.1.3 on 2018-12-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0033_auto_20181228_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='omnibuses',
            field=models.ManyToManyField(blank=True, to='Institutos.Omnibus'),
        ),
    ]
