# Generated by Django 2.0.3 on 2019-02-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0034_auto_20181231_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituto',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
    ]
