# Generated by Django 2.2.4 on 2019-08-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutos', '0035_instituto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
